### ISSUE TITLE
Welche Entwicklungen gab es in der Musikproduktion

### ISSUE THREAD

**Issue by Skipped64-inf** [r-grun/digitalisierung_musikbranche#11]
- Recherche

**Comment by chippisc** [comment]
Dokument:
https://teams.microsoft.com/_#/docx/viewer/teams/https:~2F~2Fdhbwstg.sharepoint.com~2Fsites~2Fo365grpDigitalisierungMusikbrancheSTG-TINF19B~2FFreigegebene%20Dokumente~2FGeneral~2FWelche%20Entwicklung%20gab%20es%20in%20der%20Musikproduktion.docx?threadId=19:hoYuqQRm_bt-2zYkPFmeeKxkp4d4fGpmCMoFNNSgKrg1@thread.tacv2&baseUrl=https:~2F~2Fdhbwstg.sharepoint.com~2Fsites~2Fo365grpDigitalisierungMusikbrancheSTG-TINF19B&fileId=96b516f1-1d66-4e10-8ea2-119480a8bebe&ctx=files&rootContext=items_view&viewerAction=view
