### ISSUE TITLE
Analysierbare Eigenschaften von Musik

### ISSUE THREAD

**Issue by Skipped64-inf** [r-grun/digitalisierung_musikbranche#12]
- Recherche
- Art
- Einfluss von Produktion
- Welche Methode zur Analyse ist zugeordnet

**Comment by chippisc** [comment]
Dokument in Microsoft Teams:

https://teams.microsoft.com/_#/docx/viewer/teams/https:~2F~2Fdhbwstg.sharepoint.com~2Fsites~2Fo365grpDigitalisierungMusikbrancheSTG-TINF19B~2FFreigegebene%20Dokumente~2FAnalysierbare%20Eigenschaften.docx?threadId=19:hoYuqQRm_bt-2zYkPFmeeKxkp4d4fGpmCMoFNNSgKrg1@thread.tacv2&baseUrl=https:~2F~2Fdhbwstg.sharepoint.com~2Fsites~2Fo365grpDigitalisierungMusikbrancheSTG-TINF19B&fileId=d73141d6-6804-44fa-b81d-c22cb78835f6&ctx=files&rootContext=items_view&viewerAction=editNew
