### ISSUE TITLE
Gefilterte Listen Erstellen

### ISSUE THREAD

**Issue by r-grun** [r-grun/digitalisierung_musikbranche#22]

**Comment by Sondeyy** [comment]
Provided a funtion `get_stat_filtered_by_year` in `utils.py`.

Call it the following way to get the stat you want: 
```
from utils import get_stat_filtered_by_years
import matplotlib.pyplot as plt
from hdf5_getters import get_loudness
loudness = get_stat_filtered_by_years("MillionSongSubset", get_loudness)
```
Replace `get_loudness` with the function in `hdf5_getters.py` that you need. 

The function call will return a dictionary: 
`{"tape": [], "vinyl": [], "kassette": [], "cd": [], "mp3": []}`
