### ISSUE TITLE
Essentia testen

### ISSUE THREAD

**Issue by Skipped64-inf** [r-grun/digitalisierung_musikbranche#8]
@r-grun @Sondeyy

**Comment by Sondeyy** [comment]
Lokal getestet.
z.B:
```
import essentia.standard
import matplotlib.pyplot as plt

loader = essentia.standard.MonoLoader(filename='songs/Danzig-mother.mp3')
audio = loader()

plt.plot(audio[44100:2 * 44100])
plt.show()
```

**Comment by Sondeyy** [comment]
Es muss noch geprüft werden, ob wir `essentia.standard` oder `essentia.streaming` verwenden wollen.

**Comment by r-grun** [comment]
`essentia.standard` ist hier besser; es lässt sich leichter lesen und debuggen

**Comment by r-grun** [comment]
Ein Test auf dem Jupyter NB Server wäre noch hilfreich

**Comment by Sondeyy** [comment]
Essentia no longer necessary due to datasource change.
